name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  pretty:
    name: Pretty
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx prettier . --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx --yes oxlint@0.9.10 --deny-warnings
